version: "3.8"

services:
  web:
    build: .
    ports:
      - "56632:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
